# Numpy 

## Installation
~~~bash
> pip install numpy
~~~




In [1]:
import numpy as np

In [2]:
import sys
import time

## Compare native python list and numpy

1. Memory size : numpy uses low memory

In [3]:
SIZE = 100 # 100x integers

# One Single Integer --> 4x Bytes

# Native list
mylist = range(SIZE)
print(sys.getsizeof(1) * SIZE) # Size of 100 integers --> 2800 bytes

# Numpy Array
numpy_array = np.array(SIZE)
print(numpy_array.itemsize * SIZE)  # 800x Bytes, because 8xByte/Integer * 100 Integers

2800
800


2. Execution Time : Numpy is faster than native list

In [4]:
SIZE = 1000000 # x Integers

# Add two lists together

# Python Native
mylist1 = range(SIZE)
mylist2 = range(SIZE)

start = time.time()
result = [(x+y) for x,y in zip(mylist1,mylist2)]
end = time.time()
print("Python Time:", (end-start) * 1000)

Python Time: 104.50243949890137


In [5]:
# Numpy Array
array1 = np.arange(SIZE)
array2 = np.arange(SIZE)

start = time.time()
result = array1 + array2
end = time.time()
print("Numpy Time:", (end-start) * 1000)

Numpy Time: 17.407894134521484


# Define Arrays

In [ ]:
# 1. Via native python list
mylist = [1,2,3,4,5]
print(mylist, type(mylist))

array = np.array(mylist)
print(array,type(array))


# 2. define directly one dimensional
array_1 = np.array([1,2,3,4,5])
print(array_1)

# 3. define multi dimensional array
array_2 = np.array( [ [1,2], [3,4]   ]   )
print(array_2)

In [6]:
# Define with specific data type
array_1 = np.array([1,2,3,4,5], dtype = np.float64)   # 8x bytes float
print(array_1)


array_1 = np.array([1,2,3,4,5], dtype = np.int32)   # 4x bytes int
print(array_1)




[1. 2. 3. 4. 5.]
[1 2 3 4 5]


# Array Information

In [7]:
array_1 = np.array([1,2,3,4,5])
print(array_1)

[1 2 3 4 5]


In [8]:
array_1 = np.array([1,2,3,4,5])
print(array_1)


print(array_1.shape) # (5,)  : vector with 5x elements
print(array_1.ndim) # 1
print(array_1.size) # 5x Items
print(array_1.dtype) # int32
print(array_1.itemsize) # size : 4x bytes for each item

[1 2 3 4 5]
(5,)
1
5
int64
8


In [9]:
array_2 = np.array( [ [1,2], [3,4]   ], dtype =np.float64   )
print(array_2)

print(array_2.shape) # (2,2) 2x rows  and 2x columns
print(array_2.ndim) # 2x dimensional
print(array_2.size) # 4x items
print(array_2.dtype) # float64
print(array_2.itemsize) # 8x bytes/item


[[1. 2.]
 [3. 4.]]
(2, 2)
2
4
float64
8


# Mathermatical Operations

In [ ]:
a = np.arange(10)  # 0->9
b = np.arange(1,11)  # 1->10
c = np.array( [ [1,2], [3,4] , [5,6]     ]  )

print(a + b)
print(a - b)
print(a * b)
print(a / b)

print() 


# Numpy functions
print(np.sqrt(a))


# Functions

In [11]:
c = np.array( [ [1,2], [3,4] , [5,6]     ]  )
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
a = np.arange(10)  # 0->9
b = np.arange(1,11)  # 1->10
c = np.array( [ [1,2], [3,4] , [5,6]     ]  )



# Array functions
print(a.min())
print(a.max())
print(a.mean())
print(a.sum())
print(c.sum())  # 1+2+3+4+5+6


# Advanced Sum --> Sum over columns or rows
""" 
axis = 0 : columns
axis = 1 : rows
"""

print(c.sum(axis=0))  # over columns [9 12]
print(c.sum(axis=1))  # over rows [3 7 11]





# Rounding
a = np.array([5.0,3.3,2.123,5.1547,76.781,8.8782])
print(a.round(decimals = 2)) # round all items


# Sorting
a = np.array([5,4,2,6,8,7,4])

a.sort()
print(a) # [ 2  3  5  5  8 76]


0
9
4.5
45
21
[ 9 12]
[ 3  7 11]
[ 5.    3.3   2.12  5.15 76.78  8.88]
[2 4 4 5 6 7 8]


# Accessing Items --> Slicing

In [13]:
c = np.array([[1,2], 
              [3,4], 
              [5,6]])
print(c.shape) # (3, 2)  3x Rows and 2x Columns


print(c[0])
print(c[1])
print(c[-1])
print(c[0:2])

print(c[::-1]) # rückwerts


# Specific Item
print(c[1,1]) # 4: 1x row, 1xcolumn

# Range
print(c[0:2,1:2]) # 



(3, 2)
[1 2]
[3 4]
[5 6]
[[1 2]
 [3 4]]
[[5 6]
 [3 4]
 [1 2]]
4
[[2]
 [4]]


# Generate Data

In [14]:
a = np.arange(30) # 0-29
b = np.arange(10,30) # 10-29

print(a)
print(b)

zeros = np.zeros((3,4 )) # 3x Rows, 4x Columns
print(zeros)

ones = np.ones((3,4))
print(ones)


numbers = np.linspace(1,5,50) # 50x numbers between 1 and 5, equal spaced
print(numbers)


# generate vector of 6x items with each and every value equal to 5
numbers = np.full((6,), 5) # [5 5 5 5 5 5]
print(numbers)

# generate matrix dimension 2-by-3 with each and every value equal to 5
numbers = np.full((2, 3), 5)
print(numbers)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]
[5 5 5 5 5 5]
[[5 5 5]
 [5 5 5]]


# Reshaping
- Converts the shape of an array to another **compatible** shape
- It create a new array without changing the original one

In [15]:
a = np.array( [ [1,2], 
                [3,4], 
                [5,6] ] )

print("Before Reshaping:")
print(a.shape) # (3, 2)


# 1. Reshape to 2x3
print("After  Reshaping 1:")
b = a.reshape(2,3)
print(b, b.shape)


# 2. Reshape to 6x1
print("After  Reshaping 2:")
c = a.reshape(6,1)
print(c, c.shape)


# 3. Reshape to 1x Row and 6x Columns
print("After  Reshaping 3:")
e = a.reshape(1,6)
print(e, e.shape) # [[1 2 3 4 5 6]] (1, 6)



# 4. Reshape to 6xrows 
print("After  Reshaping 4:")
d = a.reshape(6,) # Vector of 6x items without column
print(d, d.shape) # [1 2 3 4 5 6] (6,)






Before Reshaping:
(3, 2)
After  Reshaping 1:
[[1 2 3]
 [4 5 6]] (2, 3)
After  Reshaping 2:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)
After  Reshaping 3:
[[1 2 3 4 5 6]] (1, 6)
After  Reshaping 4:
[1 2 3 4 5 6] (6,)


# Flattern

In [ ]:
a = np.array([ [1,2] , [3,4] , [5,6] ])

print(a, a.shape)

result = a.ravel()
print(result, result.shape) # [1 2 3 4 5 6] (6,)


# Alternative  (.flat is an iterator)
for x in a.flat:
    print(x)


# Iteration over an array

In [ ]:
a = np.array([ [1,2] , [3,4] , [5,6] ])

for row in a:
    print(row)


for number in a.flat:
    print(number)

# Random

In [17]:
from numpy import random 

In [18]:
np.random.seed(123)

In [19]:
# signle random integer
x = random.randint(100)
print(x, type(x))

# 1x dim random array with integers
x = random.randint(100, size =(5,))
print(x, type(x))

# 1x dim random array with floats
x = random.uniform(1,100, size=(5,))

##### Choose from a list
my_list = [1,2,3,4,5,6,7, 8,9, 10]

# Single choice
x = random.choice(my_list)
print(x, type(x))

# Multiple Choice 1x Dim
x = random.choice(my_list, size= (3,))
print(x, type(x))


# Multiple Choice multix Dim
x = random.choice(my_list, size= (3,5))
print(x, type(x))

66 <class 'int'>
[92 98 17 83 57] <class 'numpy.ndarray'>
10 <class 'numpy.int64'>
[4 5 1] <class 'numpy.ndarray'>
[[ 1  5  2  8  4]
 [ 3  5  8  3  5]
 [ 9  1  8 10  4]] <class 'numpy.ndarray'>


# View

Any change to the original, the view will be affected

In [20]:
a = np.array([1,2,3,4,5])
b = a  # b will referente to the same container as a

print(a)
print(b)

# Change original
a[0] = 11
print(a)
print(b)

b[1] = 22
print(a)
print(b)

[1 2 3 4 5]
[1 2 3 4 5]
[11  2  3  4  5]
[11  2  3  4  5]
[11 22  3  4  5]
[11 22  3  4  5]


# Copy

In [21]:
# a und b sind unterschiedliche Speicher

a = np.array([1,2,3,4,5])
b = a.copy()

print(a)
print(b)
print() 

a[0] = 11
print(a)
print(b)
print()


b[0] = 11111
print(a)
print(b)


[1 2 3 4 5]
[1 2 3 4 5]

[11  2  3  4  5]
[1 2 3 4 5]

[11  2  3  4  5]
[11111     2     3     4     5]


# Vertical Stack of Data

In [22]:
a1 = np.array([[1,2],
               [3,4],
               [5,6]])

a2 = np.array([[7,8],
               [9,10],
               [10,11]])

output = np.vstack((a1, a2))
print(output)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


# Horizontal Stack of Data

In [23]:
# Add the first row of both containers togehter in one row, then next rows

a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

output = np.hstack((a1, a2))

print(output)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# Data Type Conversion

In [24]:
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

output = a.astype('int')
output = a.astype('float')
output = a.astype('float64')
output = a.astype('str')

print(output)

[['2.5' '3.8' '1.5']
 ['4.7' '2.9' '1.56']]


In [25]:
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

output = a.astype('int') # 4 bytes
# output = a.astype('int32') # 4 bytes
output = a.astype('int64') # 8 byte


output = a.astype('float') # 8 byte
output = a.astype('float64') # 8 byte

print(output)
print(output.itemsize)

[[2.5  3.8  1.5 ]
 [4.7  2.9  1.56]]
8


# the positions (indexes) where elements of 2 numpy arrays match

In [26]:
a = np.array([1,2,3,4,5])

b = np.array([1,3,2,4,5])

print(np.where(a == b))

(array([0, 3, 4]),)


# Matrix Multiplication

In [27]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

o = a@b

# Alternative
o = np.matmul(a, b)

print(o)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


# Transpose

In [28]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

output = a.T

print(output)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Sorting

In [29]:
array = np.array([10,1,5,2])

indexes = np.argsort(array)

print(indexes)

[1 3 2 0]


# Dates

In [30]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday)
print(today)
print(tomorrow)

2024-09-05
2024-09-06
2024-09-07


In [31]:
# Get Dates between two dates

Z = np.arange('2022-01-13', '2022-02-15', dtype='datetime64[D]')
print(Z)

['2022-01-13' '2022-01-14' '2022-01-15' '2022-01-16' '2022-01-17'
 '2022-01-18' '2022-01-19' '2022-01-20' '2022-01-21' '2022-01-22'
 '2022-01-23' '2022-01-24' '2022-01-25' '2022-01-26' '2022-01-27'
 '2022-01-28' '2022-01-29' '2022-01-30' '2022-01-31' '2022-02-01'
 '2022-02-02' '2022-02-03' '2022-02-04' '2022-02-05' '2022-02-06'
 '2022-02-07' '2022-02-08' '2022-02-09' '2022-02-10' '2022-02-11'
 '2022-02-12' '2022-02-13' '2022-02-14']
